import { join, relative, sep } from 'node:path';

/**
 * Default on-disk locations for the lessons subsystem.
 *
 * All artifacts live under `<projectRoot>/.agentsmesh/lessons/`, so the lessons
 * subsystem is a self-contained canonical feature — `agentsmesh init --lessons`
 * scaffolds this directory and the procedural rule, and removal is a single
 * directory delete.
 *
 * Path values are absolute; `*Rel` helpers return forward-slash project-relative
 * paths suitable for embedding in markdown rules consumed by any agent target.
 */
export interface LessonsPaths {
  /** Directory containing every lessons artifact. */
  readonly base: string;
  /** Append-only journal — point of capture for new lessons. */
  readonly journal: string;
  /** Trigger index — maps file_globs / command_patterns / keywords to topic files. */
  readonly index: string;
  /** Distill ledger — bullet hash → assigned topic (or "skip"). */
  readonly ledger: string;
  /** Distill proposal file — generated by `distill`, consumed by `distill:apply`. */
  readonly proposal: string;
  /** Directory holding one markdown file per topic cluster. */
  readonly topicsDir: string;
}

const BASE_REL = '.agentsmesh/lessons';

export function lessonsPaths(projectRoot: string): LessonsPaths {
  const base = join(projectRoot, BASE_REL);
  return {
    base,
    journal: join(base, 'journal.md'),
    index: join(base, 'index.yaml'),
    ledger: join(base, 'distill-ledger.yaml'),
    proposal: join(base, 'distill-proposal.md'),
    topicsDir: join(base, 'topics'),
  };
}

/**
 * Project-relative path for a given absolute path, normalized to forward
 * slashes for cross-platform consistency in markdown rule files.
 */
export function toRelPath(projectRoot: string, absolute: string): string {
  return relative(projectRoot, absolute).split(sep).join('/');
}

/**
 * Empty-journal contents used by init scaffolding. The journal grows from here
 * as failures get recorded.
 */
export const LESSONS_JOURNAL_TEMPLATE = '# Lessons Learned\n\n';

/**
 * Empty index used by init scaffolding. Schema allows zero clusters; topics
 * accumulate via `distill:apply` as failures are captured.
 */
export const LESSONS_INDEX_TEMPLATE = 'version: 1\nclusters: []\n';

/**
 * Procedural rule paragraph that must live in the project's root rule
 * (`.agentsmesh/rules/_root.md`) for both recall and capture to be enforced.
 *
 * Universal across every agent target: only requires the ability to read
 * project files. No `Skill` tool, no description-match, no per-target
 * projection.
 */
export const LESSONS_PROCEDURAL_RULE = `## Lessons (MUST do — non-negotiable)

Two rituals. Universal across every agent harness — described in tool-agnostic action verbs ("read a file", "edit a file", "run a shell command"); use whatever read / write-patch / shell-exec tool your harness exposes. Skipping either ritual is a process violation; the same paid-for failure recurs next session.

**Recall — BEFORE editing any file or running any shell command:**

1. Read \`.agentsmesh/lessons/index.yaml\`.
2. For every cluster whose triggers match — \`file_globs\` against the target file path, \`command_patterns\` (regex) against the shell command, or \`keywords\` (case-insensitive substring) against the active task description — read its \`file\` (e.g. \`.agentsmesh/lessons/topics/<topic>.md\`).
3. Apply the loaded rules to the action.
4. Then — and only then — perform the edit or run the command.

Rejected excuses: *"the edit is small"* → apply it. *"I read this earlier in the session"* → context may have compacted; re-read. *"no trigger fires"* → proceed; you've done your part.

**Capture — IMMEDIATELY after any failure** (test, CI, lint, code review, user correction, regression you spotted yourself, OR any mistake by anyone in the loop):

1. Append one bullet to \`.agentsmesh/lessons/journal.md\` in this exact shape:
   \`- **<short heading>**: <what went wrong>. <root cause>. <imperative rule that prevents recurrence>.\`
2. Read \`.agentsmesh/lessons/index.yaml\` and identify which topic the lesson belongs to (use the \`summary:\` fields).
3. If the lesson teaches a NEW rule: edit that topic's \`## Rules\` section to add it, citing \`(Evidence: L<journal-line>)\`. If it only reinforces an existing rule, the journal entry alone suffices.

Rejected excuses: *"it wasn't really a failure"* → if you fixed something, it was. *"I'll capture it later"* → no; do it now while context is fresh. *"no topic fits"* → still record in journal; an unrouted bullet is recoverable, a forgotten one is not.

**These two rituals are load-bearing. Treat them with the same discipline as TDD.**`;
