import { join, relative, sep } from 'node:path';

/**
 * Default on-disk locations for the lessons subsystem.
 *
 * All artifacts live under `<projectRoot>/.agentsmesh/lessons/`, so the lessons
 * subsystem is a self-contained canonical feature — `agentsmesh init --lessons`
 * scaffolds this directory and the procedural rule, and removal is a single
 * directory delete.
 *
 * Path values are absolute; `*Rel` helpers return forward-slash project-relative
 * paths suitable for embedding in markdown rules consumed by any agent target.
 */
export interface LessonsPaths {
  /** Directory containing every lessons artifact. */
  readonly base: string;
  /** Append-only journal — point of capture for new lessons. */
  readonly journal: string;
  /** Trigger index — maps file_globs / command_patterns / keywords to topic files. */
  readonly index: string;
  /** Distill ledger — bullet hash → assigned topic (or "skip"). */
  readonly ledger: string;
  /** Distill proposal file — generated by `distill`, consumed by `distill:apply`. */
  readonly proposal: string;
  /** Directory holding one markdown file per topic cluster. */
  readonly topicsDir: string;
}

const BASE_REL = '.agentsmesh/lessons';

export function lessonsPaths(projectRoot: string): LessonsPaths {
  const base = join(projectRoot, BASE_REL);
  return {
    base,
    journal: join(base, 'journal.md'),
    index: join(base, 'index.yaml'),
    ledger: join(base, 'distill-ledger.yaml'),
    proposal: join(base, 'distill-proposal.md'),
    topicsDir: join(base, 'topics'),
  };
}

/**
 * Project-relative path for a given absolute path, normalized to forward
 * slashes for cross-platform consistency in markdown rule files.
 */
export function toRelPath(projectRoot: string, absolute: string): string {
  return relative(projectRoot, absolute).split(sep).join('/');
}

/**
 * Empty-journal contents used by init scaffolding. The journal grows from here
 * as failures get recorded.
 */
export const LESSONS_JOURNAL_TEMPLATE = '# Lessons Learned\n\n';

/**
 * Empty index used by init scaffolding. Schema allows zero clusters; topics
 * accumulate via `distill:apply` as failures are captured.
 */
export const LESSONS_INDEX_TEMPLATE = 'version: 1\nclusters: []\n';

/**
 * Procedural rule paragraph that must live in the project's root rule
 * (`.agentsmesh/rules/_root.md`) for both recall and capture to be enforced.
 *
 * Universal across every agent target: only requires the ability to read
 * project files. No `Skill` tool, no description-match, no per-target
 * projection.
 */
export const LESSONS_PROCEDURAL_RULE = `## Lessons (mandatory)

- **Recall** — before editing a file or running a command, scan \`.agentsmesh/lessons/index.yaml\`. For every matched cluster, read the cluster's \`file\` (e.g. \`.agentsmesh/lessons/topics/<topic>.md\`) before proceeding. Match \`file_globs\` (path), \`command_patterns\` (command), or \`keywords\` (task text); multiple matches → read all.
- **Capture** — after every failure (test, CI, lint, code review, user correction, or one you spotted yourself), append a bullet to \`.agentsmesh/lessons/journal.md\`: **what went wrong**, **root cause**, **rule that prevents recurrence**. Then \`pnpm distill\` → review the proposal → \`pnpm distill:apply\`.

Skipping either is a process violation.`;
