export const TARGET_CONTRACTS = {
  'claude-code': {
    generated: [
      '.claude/CLAUDE.md',
      '.claude/agents/code-reviewer.md',
      '.claude/agents/researcher.md',
      '.claude/commands/review.md',
      '.claude/rules/typescript.md',
      '.claude/settings.json',
      '.claude/skills/api-generator/SKILL.md',
      '.claude/skills/api-generator/references/route-checklist.md',
      '.claude/skills/api-generator/template.ts',
      '.claudeignore',
      '.mcp.json',
    ],
    imported: [
      '.agentsbridge/agents/code-reviewer.md',
      '.agentsbridge/agents/researcher.md',
      '.agentsbridge/commands/review.md',
      '.agentsbridge/hooks.yaml',
      '.agentsbridge/ignore',
      '.agentsbridge/mcp.json',
      '.agentsbridge/permissions.yaml',
      '.agentsbridge/rules/_root.md',
      '.agentsbridge/rules/typescript.md',
      '.agentsbridge/skills/api-generator/SKILL.md',
      '.agentsbridge/skills/api-generator/references/route-checklist.md',
      '.agentsbridge/skills/api-generator/template.ts',
    ],
  },
  cursor: {
    generated: [
      '.cursor/agents/code-reviewer.md',
      '.cursor/agents/researcher.md',
      '.cursor/commands/review.md',
      '.cursor/hooks.json',
      '.cursor/mcp.json',
      '.cursor/rules/general.mdc',
      '.cursor/rules/typescript.mdc',
      '.cursor/skills/api-generator/SKILL.md',
      '.cursor/skills/api-generator/references/route-checklist.md',
      '.cursor/skills/api-generator/template.ts',
      '.cursorignore',
      'AGENTS.md',
    ],
    imported: [
      '.agentsbridge/agents/code-reviewer.md',
      '.agentsbridge/agents/researcher.md',
      '.agentsbridge/commands/review.md',
      '.agentsbridge/hooks.yaml',
      '.agentsbridge/ignore',
      '.agentsbridge/mcp.json',
      '.agentsbridge/rules/_root.md',
      '.agentsbridge/rules/typescript.md',
      '.agentsbridge/skills/api-generator/SKILL.md',
      '.agentsbridge/skills/api-generator/references/route-checklist.md',
      '.agentsbridge/skills/api-generator/template.ts',
    ],
  },
  copilot: {
    generated: [
      '.github/agents/code-reviewer.agent.md',
      '.github/agents/researcher.agent.md',
      '.github/copilot-instructions.md',
      '.github/hooks/agentsbridge.json',
      '.github/hooks/scripts/posttooluse-0.sh',
      '.github/instructions/typescript.instructions.md',
      '.github/prompts/review.prompt.md',
      '.github/skills/api-generator/SKILL.md',
      '.github/skills/api-generator/references/route-checklist.md',
      '.github/skills/api-generator/template.ts',
    ],
    imported: [
      '.agentsbridge/agents/code-reviewer.md',
      '.agentsbridge/agents/researcher.md',
      '.agentsbridge/commands/review.md',
      '.agentsbridge/hooks.yaml',
      '.agentsbridge/rules/_root.md',
      '.agentsbridge/rules/typescript.md',
      '.agentsbridge/skills/api-generator/SKILL.md',
      '.agentsbridge/skills/api-generator/references/route-checklist.md',
      '.agentsbridge/skills/api-generator/template.ts',
    ],
  },
  junie: {
    generated: [
      '.aiignore',
      '.junie/AGENTS.md',
      '.junie/agents/code-reviewer.md',
      '.junie/agents/researcher.md',
      '.junie/commands/review.md',
      '.junie/mcp/mcp.json',
      '.junie/rules/typescript.md',
      '.junie/skills/api-generator/SKILL.md',
      '.junie/skills/api-generator/references/route-checklist.md',
      '.junie/skills/api-generator/template.ts',
    ],
    imported: [
      '.agentsbridge/agents/code-reviewer.md',
      '.agentsbridge/agents/researcher.md',
      '.agentsbridge/commands/review.md',
      '.agentsbridge/ignore',
      '.agentsbridge/mcp.json',
      '.agentsbridge/rules/_root.md',
      '.agentsbridge/rules/typescript.md',
      '.agentsbridge/skills/api-generator/SKILL.md',
      '.agentsbridge/skills/api-generator/references/route-checklist.md',
      '.agentsbridge/skills/api-generator/template.ts',
    ],
  },
  'gemini-cli': {
    generated: [
      '.gemini/agents/code-reviewer.md',
      '.gemini/agents/researcher.md',
      '.gemini/commands/review.toml',
      '.gemini/policies/permissions.toml',
      '.gemini/settings.json',
      '.gemini/skills/api-generator/SKILL.md',
      '.gemini/skills/api-generator/references/route-checklist.md',
      '.gemini/skills/api-generator/template.ts',
      '.geminiignore',
      'AGENTS.md',
      'GEMINI.md',
    ],
    imported: [
      '.agentsbridge/agents/code-reviewer.md',
      '.agentsbridge/agents/researcher.md',
      '.agentsbridge/commands/review.md',
      '.agentsbridge/hooks.yaml',
      '.agentsbridge/ignore',
      '.agentsbridge/mcp.json',
      '.agentsbridge/permissions.yaml',
      '.agentsbridge/rules/_root.md',
      '.agentsbridge/skills/api-generator/SKILL.md',
      '.agentsbridge/skills/api-generator/references/route-checklist.md',
      '.agentsbridge/skills/api-generator/template.ts',
    ],
  },
  cline: {
    generated: [
      '.cline/mcp_settings.json',
      '.cline/skills/ab-agent-code-reviewer/SKILL.md',
      '.cline/skills/ab-agent-researcher/SKILL.md',
      '.cline/skills/api-generator/SKILL.md',
      '.cline/skills/api-generator/references/route-checklist.md',
      '.cline/skills/api-generator/template.ts',
      '.clineignore',
      '.clinerules/hooks/posttooluse-0.sh',
      '.clinerules/typescript.md',
      '.clinerules/workflows/review.md',
      'AGENTS.md',
    ],
    imported: [
      '.agentsbridge/agents/code-reviewer.md',
      '.agentsbridge/agents/researcher.md',
      '.agentsbridge/commands/review.md',
      '.agentsbridge/ignore',
      '.agentsbridge/mcp.json',
      '.agentsbridge/rules/_root.md',
      '.agentsbridge/rules/typescript.md',
      '.agentsbridge/skills/api-generator/SKILL.md',
      '.agentsbridge/skills/api-generator/references/route-checklist.md',
      '.agentsbridge/skills/api-generator/template.ts',
    ],
  },
  'codex-cli': {
    generated: [
      '.agents/skills/ab-command-review/SKILL.md',
      '.agents/skills/api-generator/SKILL.md',
      '.agents/skills/api-generator/references/route-checklist.md',
      '.agents/skills/api-generator/template.ts',
      '.codex/agents/code-reviewer.toml',
      '.codex/agents/researcher.toml',
      '.codex/config.toml',
      'AGENTS.md',
      'src/AGENTS.md',
    ],
    imported: [
      '.agentsbridge/agents/code-reviewer.md',
      '.agentsbridge/agents/researcher.md',
      '.agentsbridge/commands/review.md',
      '.agentsbridge/mcp.json',
      '.agentsbridge/rules/_root.md',
      '.agentsbridge/rules/src.md',
      '.agentsbridge/skills/api-generator/SKILL.md',
      '.agentsbridge/skills/api-generator/references/route-checklist.md',
      '.agentsbridge/skills/api-generator/template.ts',
    ],
  },
  windsurf: {
    generated: [
      '.codeiumignore',
      '.windsurf/hooks.json',
      '.windsurf/mcp_config.example.json',
      '.windsurf/rules/typescript.md',
      '.windsurf/skills/ab-agent-code-reviewer/SKILL.md',
      '.windsurf/skills/ab-agent-researcher/SKILL.md',
      '.windsurf/skills/api-generator/SKILL.md',
      '.windsurf/skills/api-generator/references/route-checklist.md',
      '.windsurf/skills/api-generator/template.ts',
      '.windsurf/workflows/review.md',
      'AGENTS.md',
      'src/AGENTS.md',
    ],
    imported: [
      '.agentsbridge/agents/code-reviewer.md',
      '.agentsbridge/agents/researcher.md',
      '.agentsbridge/commands/review.md',
      '.agentsbridge/hooks.yaml',
      '.agentsbridge/ignore',
      '.agentsbridge/mcp.json',
      '.agentsbridge/rules/_root.md',
      '.agentsbridge/rules/src.md',
      '.agentsbridge/rules/typescript.md',
      '.agentsbridge/skills/api-generator/SKILL.md',
      '.agentsbridge/skills/api-generator/references/route-checklist.md',
      '.agentsbridge/skills/api-generator/template.ts',
    ],
  },
} as const;

export const TARGET_SPECIFIC_PREFIXES = [
  '.claude/',
  '.cursor/',
  '.github/',
  '.junie/',
  '.gemini/',
  '.cline/',
  '.agents/',
  '.windsurf/',
] as const;
