/**
 * Cursor skills import helpers — directory-structured and flat skill imports.
 */

import { join, basename, dirname, relative } from 'node:path';
import type { ImportResult } from '../../core/types.js';
import { readFileSafe, readDirRecursive, writeFileAtomic, mkdirp } from '../../utils/fs.js';

const CURSOR_SKILLS_DIR = '.cursor/skills';
const AB_SKILLS = '.agentsbridge/skills';

/**
 * Import Cursor skills. Handles two formats:
 *   Directory-structured (generated by agentsbridge):
 *     .cursor/skills/{name}/SKILL.md + supporting files → .agentsbridge/skills/{name}/...
 *   Flat (native Cursor format):
 *     .cursor/skills/{name}.md → .agentsbridge/skills/{name}/SKILL.md
 */
export async function importSkills(
  projectRoot: string,
  results: ImportResult[],
  normalize: (content: string, sourceFile: string, destinationFile: string) => string,
): Promise<void> {
  const destBase = join(projectRoot, AB_SKILLS);
  const skillsDir = join(projectRoot, CURSOR_SKILLS_DIR);
  const allFiles = await readDirRecursive(skillsDir);
  const mdFiles = allFiles.filter((f) => f.endsWith('.md'));

  // Directory-structured: find SKILL.md files; skill name = parent directory
  const skillMdFiles = mdFiles.filter((f) => basename(f) === 'SKILL.md');
  const handledPaths = new Set<string>();

  for (const skillMdPath of skillMdFiles) {
    const skillDir = dirname(skillMdPath);
    const skillName = basename(skillDir);
    const destSkillDir = join(destBase, skillName);
    const skillFiles = await readDirRecursive(skillDir);
    for (const filePath of skillFiles) {
      handledPaths.add(filePath);
      const content = await readFileSafe(filePath);
      if (content === null) continue;
      const relPath = relative(skillDir, filePath);
      const destPath = join(destSkillDir, relPath);
      await mkdirp(dirname(destPath));
      await writeFileAtomic(destPath, normalize(content, filePath, destPath));
      results.push({
        fromTool: 'cursor',
        fromPath: filePath,
        toPath: `${AB_SKILLS}/${skillName}/${relPath}`,
        feature: 'skills',
      });
    }
  }

  // Flat: remaining .md files not already handled above
  for (const srcPath of mdFiles) {
    if (handledPaths.has(srcPath)) continue;
    const content = await readFileSafe(srcPath);
    if (!content) continue;
    const name = basename(srcPath, '.md');
    const destSkillDir = join(destBase, name);
    await mkdirp(destSkillDir);
    const destPath = join(destSkillDir, 'SKILL.md');
    await writeFileAtomic(destPath, normalize(content, srcPath, destPath));
    results.push({
      fromTool: 'cursor',
      fromPath: srcPath,
      toPath: `${AB_SKILLS}/${name}/SKILL.md`,
      feature: 'skills',
    });
  }
}
