/**
 * Cursor skills import helpers — directory-structured and flat skill imports.
 */

import { join, basename, dirname, relative } from 'node:path';
import type { ImportResult } from '../../core/types.js';
import {
  readFileSafe,
  readDirRecursive,
  writeFileAtomic,
  mkdirp,
} from '../../utils/filesystem/fs.js';
import { parseFrontmatter } from '../../utils/text/markdown.js';
import { serializeImportedSkillWithFallback } from '../import/import-metadata.js';
import { CURSOR_SKILLS_DIR, CURSOR_CANONICAL_SKILLS_DIR } from './constants.js';

/**
 * Import Cursor skills. Handles two formats:
 *   Directory-structured (generated by agentsmesh):
 *     .cursor/skills/{name}/SKILL.md + supporting files → .agentsmesh/skills/{name}/...
 *   Flat (native Cursor format):
 *     .cursor/skills/{name}.md → .agentsmesh/skills/{name}/SKILL.md
 */
export async function importSkills(
  projectRoot: string,
  results: ImportResult[],
  normalize: (content: string, sourceFile: string, destinationFile: string) => string,
  skillsRelDir: string = CURSOR_SKILLS_DIR,
): Promise<void> {
  const destBase = join(projectRoot, CURSOR_CANONICAL_SKILLS_DIR);
  const skillsDir = join(projectRoot, skillsRelDir);
  const allFiles = await readDirRecursive(skillsDir);
  const mdFiles = allFiles.filter((f) => f.endsWith('.md'));

  // Directory-structured: find SKILL.md files; skill name = parent directory
  const skillMdFiles = mdFiles.filter((f) => basename(f) === 'SKILL.md');
  const handledPaths = new Set<string>();

  for (const skillMdPath of skillMdFiles) {
    const skillDir = dirname(skillMdPath);
    const skillName = basename(skillDir);
    const destSkillDir = join(destBase, skillName);
    const skillFiles = await readDirRecursive(skillDir);
    for (const filePath of skillFiles) {
      handledPaths.add(filePath);
      const content = await readFileSafe(filePath);
      if (content === null) continue;
      const relPath = relative(skillDir, filePath);
      const destPath = join(destSkillDir, relPath);
      await mkdirp(dirname(destPath));
      const normalized = normalize(content, filePath, destPath);
      const parsed = relPath === 'SKILL.md' ? parseFrontmatter(normalized) : null;
      await writeFileAtomic(
        destPath,
        relPath === 'SKILL.md'
          ? await serializeImportedSkillWithFallback(
              destPath,
              { ...(parsed?.frontmatter ?? {}), name: skillName },
              parsed?.body ?? '',
            )
          : normalized,
      );
      results.push({
        fromTool: 'cursor',
        fromPath: filePath,
        toPath: `${CURSOR_CANONICAL_SKILLS_DIR}/${skillName}/${relPath}`,
        feature: 'skills',
      });
    }
  }

  // Flat: remaining .md files not already handled above
  for (const srcPath of mdFiles) {
    if (handledPaths.has(srcPath)) continue;
    const content = await readFileSafe(srcPath);
    if (!content) continue;
    const name = basename(srcPath, '.md');
    const destSkillDir = join(destBase, name);
    await mkdirp(destSkillDir);
    const destPath = join(destSkillDir, 'SKILL.md');
    const normalized = normalize(content, srcPath, destPath);
    const { frontmatter, body } = parseFrontmatter(normalized);
    await writeFileAtomic(
      destPath,
      await serializeImportedSkillWithFallback(destPath, { ...frontmatter, name }, body),
    );
    results.push({
      fromTool: 'cursor',
      fromPath: srcPath,
      toPath: `${CURSOR_CANONICAL_SKILLS_DIR}/${name}/SKILL.md`,
      feature: 'skills',
    });
  }
}
