/**
 * Backward-compat cleanup for AGENTS.md content generated by older agentsmesh
 * versions, which appended an "Additional Rule Files" index (linking to a
 * `.codex/instructions/*.md` mirror Codex never actually read) to the root
 * file. The generator no longer emits that index (see generator/rules.ts and
 * codex-rule-paths.ts — advisory rules now nest as real `AGENTS.md` /
 * `AGENTS.override.md` files Codex's directory walk loads), but old repos may
 * still have one on disk; strip it on import so it doesn't round-trip forever.
 */

import { CODEX_RULE_INDEX_END, CODEX_RULE_INDEX_START } from './constants.js';

export function stripCodexRuleIndex(content: string): string {
  const escapedStart = CODEX_RULE_INDEX_START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const escapedEnd = CODEX_RULE_INDEX_END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return content
    .replace(new RegExp(`\\n?${escapedStart}[\\s\\S]*?${escapedEnd}\\n?`, 'g'), '\n')
    .trim();
}
