/**
 * Auto-discovers builtin targets under `src/targets/<name>/index.ts` and keeps
 * the catalog in sync:
 *
 *   - Writes `src/targets/catalog/builtin-target-ids-generated.ts` (string-only
 *     id list — no descriptor imports, preserves the schema↔descriptor cycle
 *     break documented in `target-ids.ts`).
 *
 *   - Patches the AUTO-GENERATED region of
 *     `src/targets/catalog/builtin-targets.ts` (the descriptor imports + the
 *     `BUILTIN_TARGETS` array literal) between sentinel comments. Inlining
 *     keeps the original module shape so existing import cycles continue to
 *     resolve through ESM live bindings.
 *
 * Adding a new target: drop a directory under `src/targets/<name>/` with an
 * `index.ts` exporting `descriptor`, then run `pnpm catalog:generate` (or
 * `pnpm build`, which triggers it via `prebuild`).
 *
 * Usage:
 *   pnpm exec tsx scripts/generate-target-catalog.ts            # writes files
 *   pnpm exec tsx scripts/generate-target-catalog.ts --verify   # exits 1 on drift
 */

import { readdirSync, readFileSync, statSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const TARGETS_DIR = join(REPO_ROOT, 'src', 'targets');
const CATALOG_DIR = join(TARGETS_DIR, 'catalog');
const NON_TARGET_DIRS = new Set(['catalog', 'import', 'projection']);

const IDS_HEADER = [
  '// AUTO-GENERATED by scripts/generate-target-catalog.ts.',
  '// Do not edit by hand — run `pnpm catalog:generate` to refresh.',
  '',
].join('\n');

const IMPORT_BEGIN = '// <auto-generated:builtin-target-imports>';
const IMPORT_END = '// </auto-generated:builtin-target-imports>';
const ARRAY_BEGIN = '// <auto-generated:builtin-targets-array>';
const ARRAY_END = '// </auto-generated:builtin-targets-array>';
const MAP_EXPORTS_BEGIN = '// <auto-generated:import-map-exports>';
const MAP_EXPORTS_END = '// </auto-generated:import-map-exports>';

const IMPORT_MAPS_DIR = join(REPO_ROOT, 'src', 'core', 'reference', 'import-maps');

function discoverTargetDirs(): string[] {
  return readdirSync(TARGETS_DIR)
    .filter((entry) => {
      const full = join(TARGETS_DIR, entry);
      return (
        statSync(full).isDirectory() &&
        !NON_TARGET_DIRS.has(entry) &&
        existsSync(join(full, 'index.ts'))
      );
    })
    .sort();
}

function assertHasDescriptorExport(dir: string): void {
  const indexPath = join(TARGETS_DIR, dir, 'index.ts');
  const source = readFileSync(indexPath, 'utf-8');
  if (!/export\s+const\s+descriptor\b/.test(source)) {
    throw new Error(
      `Target "${dir}" is missing \`export const descriptor\` in ${indexPath}. ` +
        `Every directory under src/targets/ (except ${[...NON_TARGET_DIRS].join(', ')}) ` +
        `must export a TargetDescriptor.`,
    );
  }
}

function safeIdentifier(dir: string): string {
  // 'gemini-cli' -> 'geminiCli'; 'roo-code' -> 'rooCode'; 'continue' -> 'continueTarget' (reserved word).
  const camel = dir.replace(/-([a-z0-9])/g, (_, ch: string) => ch.toUpperCase());
  return camel === 'continue' ? 'continueTarget' : camel;
}

function toPascal(dir: string): string {
  return dir
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function dirsWithImportMaps(dirs: readonly string[]): string[] {
  return dirs.filter((d) => existsSync(join(IMPORT_MAPS_DIR, `${d}.ts`)));
}

function renderImportMapBarrel(dirs: readonly string[]): string {
  return [
    MAP_EXPORTS_BEGIN,
    ...dirs.map((d) => `export { build${toPascal(d)}ImportPaths } from './${d}.js';`),
    MAP_EXPORTS_END,
  ].join('\n');
}

function renderIdsFile(dirs: readonly string[]): string {
  const literals = dirs.map((d) => `  '${d}',`).join('\n');
  return `${IDS_HEADER}/**
 * Generated catalog of builtin target IDs (directory names under \`src/targets/\`).
 * No descriptor imports — keeps this module on the schema-safe side of the
 * \`schema.ts → descriptors → ValidatedConfig → schema.ts\` cycle.
 */
export const BUILTIN_TARGET_IDS = [
${literals}
] as const;

export type BuiltinTargetId = (typeof BUILTIN_TARGET_IDS)[number];

export function isBuiltinTargetId(value: string): value is BuiltinTargetId {
  return (BUILTIN_TARGET_IDS as readonly string[]).includes(value);
}
`;
}

function renderImportBlock(dirs: readonly string[]): string {
  return [
    IMPORT_BEGIN,
    ...dirs.map((d) => `import { descriptor as ${safeIdentifier(d)} } from '../${d}/index.js';`),
    IMPORT_END,
  ].join('\n');
}

function renderArrayBlock(dirs: readonly string[]): string {
  return [
    ARRAY_BEGIN,
    'export const BUILTIN_TARGETS: readonly TargetDescriptor[] = [',
    ...dirs.map((d) => `  ${safeIdentifier(d)},`),
    '];',
    ARRAY_END,
  ].join('\n');
}

function replaceMarkedBlock(
  source: string,
  begin: string,
  end: string,
  replacement: string,
  filePath: string,
): string {
  const beginIdx = source.indexOf(begin);
  const endIdx = source.indexOf(end);
  if (beginIdx === -1 || endIdx === -1 || endIdx < beginIdx) {
    throw new Error(
      `Catalog markers \`${begin}\` / \`${end}\` not found in ${filePath}. ` +
        `Add them around the descriptor imports / array so codegen can patch them.`,
    );
  }
  const before = source.slice(0, beginIdx);
  const after = source.slice(endIdx + end.length);
  return `${before}${replacement}${after}`;
}

function writeIfChanged(path: string, content: string, verify: boolean): boolean {
  const existing = existsSync(path) ? readFileSync(path, 'utf-8') : null;
  if (existing === content) return false;
  if (verify) {
    process.stderr.write(
      `Catalog drift: ${path} is out of date. Run \`pnpm catalog:generate\` to refresh.\n`,
    );
    return true;
  }
  writeFileSync(path, content);
  process.stdout.write(`✓ wrote ${path}\n`);
  return false;
}

function main(): void {
  const verify = process.argv.includes('--verify');
  const dirs = discoverTargetDirs();
  for (const dir of dirs) assertHasDescriptorExport(dir);

  const idsPath = join(CATALOG_DIR, 'builtin-target-ids-generated.ts');
  const builtinPath = join(CATALOG_DIR, 'builtin-targets.ts');

  const builtinSource = readFileSync(builtinPath, 'utf-8');
  const withImports = replaceMarkedBlock(
    builtinSource,
    IMPORT_BEGIN,
    IMPORT_END,
    renderImportBlock(dirs),
    builtinPath,
  );
  const withArray = replaceMarkedBlock(
    withImports,
    ARRAY_BEGIN,
    ARRAY_END,
    renderArrayBlock(dirs),
    builtinPath,
  );

  const importMapIndexPath = join(IMPORT_MAPS_DIR, 'index.ts');
  const mapDirs = dirsWithImportMaps(dirs);
  const importMapSource = readFileSync(importMapIndexPath, 'utf-8');
  const patchedImportMap = replaceMarkedBlock(
    importMapSource,
    MAP_EXPORTS_BEGIN,
    MAP_EXPORTS_END,
    renderImportMapBarrel(mapDirs),
    importMapIndexPath,
  );

  const drifted =
    Number(writeIfChanged(idsPath, renderIdsFile(dirs), verify)) +
    Number(writeIfChanged(builtinPath, withArray, verify)) +
    Number(writeIfChanged(importMapIndexPath, patchedImportMap, verify));

  if (verify && drifted > 0) process.exit(1);
  if (!verify) process.stdout.write(`\nCatalog: ${dirs.length} builtin targets\n`);
}

main();
