/**
 * Minimal hand-written ESM plugin fixture.
 * Exports a single TargetDescriptor that generates PLUGIN.md.
 * Kept as .js (not TypeScript) so the dynamic-import path in load-plugin.ts is exercised.
 */

/* eslint-disable no-unused-vars */

export const descriptor = {
  id: 'simple-plugin',
  generators: {
    name: 'simple-plugin',
    generateRules(canonical) {
      void canonical;
      return [{ path: 'PLUGIN.md', content: '# Simple Plugin\n\nGenerated by simple-plugin.\n' }];
    },
    async importFrom(_projectRoot, _options) {
      return [];
    },
  },
  capabilities: {
    rules: 'native',
    additionalRules: 'none',
    commands: 'none',
    agents: 'none',
    skills: 'none',
    mcp: 'none',
    hooks: 'none',
    ignore: 'none',
    permissions: 'none',
  },
  emptyImportMessage: 'No simple-plugin config found.',
  lintRules: null,
  project: {
    managedOutputs: { dirs: [], files: ['PLUGIN.md'] },
    paths: {
      rulePath(slug, _rule) { return 'PLUGIN.md'; },
      commandPath(_name, _config) { return null; },
      agentPath(_name, _config) { return null; },
    },
  },
  buildImportPaths: async (_refs, _projectRoot, _scope) => {},
  detectionPaths: [],
};
